### ISSUE TITLE
Bounty: Conflux  DAO社区技术委员会官方网站建设任务

### ISSUE THREAD

**Issue by xiaods** [Conflux-DAO-TOC/website#1]
要求：
1、使用本repo作为Fork仓库地址，并且使用静态网站技术如react，hugo等技术构建
2、自行设计网站风格并完成网站实现，要求代码完全开源
3、素材请从这里开始：https://github.com/Conflux-DAO-TOC/toc
4、可以使用好看的静态网站模板作为基础。

提供 **4000** FC (约 **400** USDT) Token支持。

验收：
1、静态网站可以正常运行。建议采用https://www.netlify.com/ 帮我们直接发布就好
2、颜色，设计样式只要合适就行，不做技术要求
3、直接fork，然后给我PR。我通过后，直接给Merged，并支付token

**Comment by xiaods** [comment]
欢迎Fork

**Comment by ysqi** [comment]
报名

**Comment by guanzizai288** [comment]
报名，搞~~

**Comment by xiaods** [comment]
@ysqi  先到先得
本次Bounty，审核通过给 @ysqi 制作。有什么问题，请直接回复此issue

**Comment by ysqi** [comment]
已 RP，见 #2

**Comment by xiaods** [comment]
@ysqi 请提供Conflux账号，我来转账。

**Comment by xiaods** [comment]
@ysqi  已转转账，请查收。

**Comment by ysqi** [comment]
已收到，谢谢。
